[package]
name = "pulz-schedule"
description = "For scheduling systems and managing their resources"
version = "0.1.0-alpha"
authors = ["Christoph Hommelsheim <main@chommel.eu>"]
license = "MIT OR Apache-2.0"
keywords = ["ecs", "systems", "schedule", "resources"]
categories = ["data-structures", "game-engines", "game-development", "asynchronous"]
repository = "https://github.com/HellButcher/pulz.git"
readme = "README.md"
edition = "2021"


[dependencies]
pulz-executor = { version = "0.1.0-alpha", path = "../executor" }
atomic_refcell = "0.1"
downcast-rs = "1.2"
tinybox = "0.2"

[target.'cfg(not(target_os = "unknown"))'.dev-dependencies]
pulz-executor = { version = "0.1.0-alpha", path = "../executor", features = ["async-std"] }
async-std = { version = "1.12", features = ["attributes"] }
