[package]
name = "pulz-schedule"
version = "0.1.0"
authors = ["Christoph Hommelsheim <main@chommel.eu>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/HellButcher/pulz.git"
readme = "README.md"
edition = "2021"


[dependencies]
pulz-arena = { path = "../arena" }
pulz-executor = { path = "../executor" }
atomic_refcell = "0.1"

[dev-dependencies]
pulz-executor = { path = "../executor", features = ["async-std"] }
async-std = { version = "1.10", features = ["attributes"] }
