[package]
name = "benches"
version = "0.1.0"
edition = "2021"
publish = false


[dev-dependencies]
pulz-ecs = { path = "../crates/ecs" }
bevy_ecs = "0.8"

criterion = { version = "0.4", features = [ "html_reports" ] }
criterion-cpu-time  = "0.1"

[[bench]]
name = "ecs_world"
harness = false
