name: Bloat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bloat:
    name: Bloat
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Cache cargo registry & index
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-index-${{ runner.os }}-${{ hashFiles('**/Cargo.*') }}
    - name: Cache cargo bloat
      uses: actions/cache@v2
      with:
        path: target
        key: cargo-bloat-${{ runner.os }}-${{ hashFiles('**/Cargo.*') }}
    - name: Bloat
      uses: orf/cargo-bloat-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
